### PR TITLE
chore: change to author

### PR DESCRIPTION
**Pull request by m-muecke**
@be-marc check if that's fine for you

### CODE REVIEW

**Comment by be-marc** [comment]
Great that you continue this

**Comment by be-marc** [comment]
When submitting to CRAN add something like this to cran-comments.md: We would like to change the author

**Comment by m-muecke** [comment]
> When submitting to CRAN add something like this to cran-comments.md: We would like to change the author

But I've changed to author not maintainer?

**Comment by be-marc** [comment]
Ah sorry. Damir ask a few days ago if someone wants to be the maintainer. Maybe you want to?

**Pull request merged**
