### PR TITLE
test with new paradox

### PR DESCRIPTION
**Pull request by mb706**

### CODE REVIEW

**Comment by m-muecke** [comment]
Ah haven't seen your PR, I have made the same changes, but refactored a bit more would recommend to go for that PR instead: https://github.com/mlr-org/mlr3cluster/pull/49

**Comment by mb706** [comment]
@damirpolat this PR prepares for the upcoming paradox release, which can already be seen on github: mlr-org/paradox. The new version will throw an error when a parameter has a 'default' value and also has the 'required' tag. This is because the semantics of the 'default' value is "what does this parameter behave like when it is *not* set" -- this is in contradiction with the "required" tag, which indicates that a parameter must always be set.
Besides that, there is also a new workflow which checks against the github version of paradox. This is because paradox on github will not be merged for a few more weeks (until all the other changes are on CRAN and other package maintainers had their time to follow suit). Until then, it is best to check both against CRAN as well as github versions of various packages.

**Comment by mb706** [comment]
Please merge this PR if you are fine with it.

**Comment by mb706** [comment]
(I think you should also put it on CRAN soon, so paradox can then be updated without causing revdep failures)

**Comment by m-muecke** [comment]
@mb706 why did you remove the crate function for the custom checks, does it not have an effect here?

**Comment by mb706** [comment]
The `crate()`s are not necessary for functions that are defined in the package. We do `crate()` for anonymous `custom_check` functions that are defined in-place to remove their environment -- otherwise the resulting objects keep the environment of the `initialize()` call around. That is not necessary here.

**Comment by m-muecke** [comment]
> The `crate()`s are not necessary for functions that are defined in the package. We do `crate()` for anonymous `custom_check` functions that are defined in-place to remove their environment -- otherwise the resulting objects keep the environment of the `initialize()` call around. That is not necessary here.

That means `custom_check = crate(function(x) check_numeric(x)))` can be changed to `custom_check = check_numeric` and only required for the inplace anonymous function?

**Comment by mb706** [comment]
Yes, putting checkmate check_-functions inside anonymous functions is only necessary if you want to combine different checks, or if you want to modify the error message. But if you do use anonymous functions, crate() should be used.

**Comment by mb706** [comment]
@damirpolat I am done here, you resolve the conflicts, merge andput the package on cran.

**Comment by damirpolat** [comment]
Thank you for your pull request! It is merged now.

**Pull request merged**
